// Default values for ModalSheet component
export const DEFAULT_VALUES = {
  MIN_HEIGHT: 150,
  DEFAULT_MAX_HEIGHT_PERCENTAGE: 0.9,
  DEFAULT_BORDER_RADIUS: 20,
  DEFAULT_BACKGROUND_COLOR: 'white',
  DEFAULT_HANDLE_COLOR: '#DDD',
  DEFAULT_BACKDROP_OPACITY: 0.5,
  DEFAULT_DRAG_THRESHOLD: 50,
  DEFAULT_ANIMATION_DURATION: 250,
  DEFAULT_SPRING_DAMPING: 20,
  DEFAULT_INITIAL_SNAP_INDEX: 0,
  DEFAULT_SCROLL_EXPAND_THRESHOLD: 50,
} as const;
